---
- hosts: "{{ target_hosts }}"
  gather_facts: true
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:
    products: [
                {"product": "com.ibm.websphere.ND.v85_8.5.5017.20200205_1450", "link": "http://b01lvi21539180.ahe.pok.ibm.com/installers/was/wasfix/"},
                {"product": "com.ibm.websphere.IHS.v85_8.5.5017.20200205_1450", "link": "http://b01lvi21539180.ahe.pok.ibm.com/installers/was/supplements/"},
                {"product": "com.ibm.websphere.PLG.v85_8.5.5017.20200205_1450", "link": "http://b01lvi21539180.ahe.pok.ibm.com/installers/was/supplements/"}
              ]


  tasks:
  - name: Install WAS Fix Pack
    ibmim:
      name: "{{ item['product'] }}"
      repositories:
      - "{{ item['link'] }}"
    with_items:
      - "{{ products }}"
    register: UpdateResults

#  - name: Debug
    debug:
      msg: "{{ UpdateResults }}"

